import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Test from "../models/testModel"
import connectMongo from '../utils/connectMongo';

export default function Home({ test }) {

  const [userData, setUserData] = useState(test)
  const createTest = async () => {
    const rondomNumber = Math.floor(Math.random() * 1000)
    const res = await fetch("/api/test/add", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: `Test  ${rondomNumber}`,
        email: `Nasir ${rondomNumber}@test.com`
      })
    })
    const data = await res.json()

  }
  const DeleteData = (ind) => {
    console.log(ind)
    const deldata = userData.filter((dat, indd) => {
      return indd != ind;
    })
    console.log(deldata)
    setUserData(deldata)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js
        </h1>
        <div className={styles.grid}>
          {
            userData?.map((userData, ind) => {
              return <div key={ind} className={styles.card} onClick={() => DeleteData(ind)}>
                <h2>Name : {userData.name} &rarr;</h2>
                <p>Email : {userData.email}</p>
              </div>
            })
          }

        </div>
        <button onClick={createTest}>Create </button>
      </main>

    </div>
  )
}


export const getServerSideProps = async () => {
  try {
    console.log("Connecting to Mongoose")
    await connectMongo()
    console.log("Connected to Mongoose Succesfully")
    console.log("Fetching Document")
    const test = await Test.find()
    console.log("fetched Document Succesfully")

    return {
      props: {
        test: JSON.parse(JSON.stringify(test))
      }
    }

  } catch (error) {
    console.log(error)
  }


}